import json,hashlib
from pathlib import Path
import importlib.util
spec=importlib.util.spec_from_file_location('src_contract',Path(__file__).parents[1]/'panel_exp/contracts/geox_calibration_handoff_source.py'); mod=importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
GeoXCalibrationHandoffSourceRecord=mod.GeoXCalibrationHandoffSourceRecord; SCHEMA=mod.SCHEMA; VERSION=mod.VERSION; CHECKPOINT=mod.CHECKPOINT; BASE=mod.BASE; checksum=mod.checksum
ROOT=Path(__file__).parents[1]; SRC=ROOT/'tests/fixtures/geox_governed_readouts'; OUT=ROOT/'tests/fixtures/geox_calibration_handoff_sources/v1/manifest.json'
def main():
 cases=json.loads((SRC/'manifest.json').read_text())['cases']; records=[]
 for c in cases:
  fid=c['case_id']; d=SRC/fid; r=json.loads((d/'governed_readout.json').read_text()); rec={"schema_version":SCHEMA,"record_version":VERSION,"handoff_source_id":f"geox-calibration-source-{fid}-v1","evidence_artifact_id":f"geox-evidence-{fid}-v1","source_readout_id":r['readout_id'],"source_readout_version":r['readout_version'],"source_artifact_version":r['artifact_version'],"experiment_id":r['experiment_id'],"fixture_id":fid,"dataset_version":r['dataset_version'],"truth_version":r['truth_version'],"source_repository":"Phani-Pavuluri/panel_exp","source_fixture_checkpoint_sha":CHECKPOINT,"task_source_tree_base_sha":BASE,"governed_readout_path":f"{fid}/governed_readout.json","governed_readout_sha256":checksum(d/'governed_readout.json'),"source_truth_path":f"{fid}/source_truth.json","source_truth_sha256":checksum(d/'source_truth.json'),"replay_path":f"{fid}/replay.json","replay_sha256":checksum(d/'replay.json'),"fixture_class":json.loads((d/'source_truth.json').read_text()).get('fixture_class','certified'),"certification_status":r.get('method_status',''),"mip_handoff_expectation":json.loads((d/'source_truth.json').read_text()).get('mip_handoff_expectation',{}),"kpi":r['kpi'],"kpi_units":r['kpi_units'],"estimand":r['estimand'],"effect_scale":r['effect_scale'],"channel":r['channel'],"tactic":r['tactic'],"geography_scope":r['geography_scope'],"geo_grain":r['geo_grain'],"time_window":r['time_window'],"pre_period":r['pre_period'],"post_period":r['post_period'],"effect_estimate":r['effect_estimate'],"absolute_lift":r['absolute_lift'],"relative_lift":r['relative_lift'],"incremental_outcome":r['incremental_outcome'],"uncertainty_available":r['uncertainty_available'],"standard_error":r['standard_error'],"confidence_interval":r['confidence_interval'],"interval_semantics":r['interval_semantics'],"time_window_start":"2025-01-06T00:00:00Z","time_window_end":"2025-03-30T23:59:59Z","produced_at":"2025-03-31T00:00:00Z","freshness_evaluated_at":"2025-03-31T00:00:00Z","synthetic_fixture_time_scope":True,"method_family":r['method_family'],"source_method_status":r['method_status'],"instrument_id":r['instrument_id'],"design_type":r['design_type'],"feasibility_status":r['feasibility_status'],"readout_status":r['readout_status'],"freshness_status":r['freshness_status'],"handoff_eligibility_status":r['handoff_eligibility_status'],"warnings":r['warnings'],"blocked_reasons":r['blocked_reasons'],"failure_reasons":r['failure_reasons'],"lineage":r['lineage'],"provenance":r['provenance'],"replay_metadata":r['replay_metadata'],"producer_package_version":r['producer_package_version'],"embedded_producer_commit":r['producer_commit'],"authorization_flags":r['authorization_flags']}; records.append(GeoXCalibrationHandoffSourceRecord.parse(rec).to_dict())
 OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(json.dumps({'schema_version':SCHEMA,'record_version':VERSION,'records':records},sort_keys=True,indent=2)+'\n')
if __name__=='__main__': main()
